# Site Settings
title: It Just Clicks Launcher
description: Documentation for the It Just Clicks Launcher
url: "https://wavrusawi-tech.github.io"
baseurl: "/itjustclicks-launcher"

# Theme Config
remote_theme: just-the-docs/just-the-docs

# Optional: Enable built-in search and dark mode/auto color scheme
search_enabled: true
color_scheme: "auto"
