# Generated by Django 6.1.1 on 2026-09-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_rating', models.CharField(choices=[('E', 'Everyone'), ('E10', 'Everyone 10+'), ('T', 'Teen'), ('MATURE17', 'Mature 17+'), ('AO', 'Adults Only'), ('RP', 'Rating Pending'), ('RP17', 'Rating Pending (Likely Mature 17+)')], default='RP', max_length=30)),
            ],
        ),
    ]
