# Generated by Django 6.1.1 on 2026-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
